version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: your-db-user
      WORDPRESS_DB_PASSWORD: your-db-password
      WORDPRESS_DB_NAME: your-db-name

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-password
      MYSQL_DATABASE: wordpress-database
      MYSQL_USER: wordpress-user
      MYSQL_PASSWORD: wordpress-password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
